apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojee
  template:
    metadata:
      labels:
        app: emojee
    spec:
      containers:
      - name: emojee
        image: us-east1-docker.pkg.dev/somestuff-dev/emojee-repo/emojee:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "0.5Gi"
            cpu: "250m"
            ephemeral-storage: "1Gi"